// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWlBe-8scWm4Zb6W1nmNtH3QZSt3LMrT0',
    appId: '1:848467584016:web:b0909e0eda21e6911ad695',
    messagingSenderId: '848467584016',
    projectId: 'restaurant-project-237e9',
    authDomain: 'restaurant-project-237e9.firebaseapp.com',
    storageBucket: 'restaurant-project-237e9.firebasestorage.app',
    measurementId: 'G-PPN6K3RV79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZ1r1ne_7-Wr9Grx-UB_6lJDIGE6Cz-s',
    appId: '1:848467584016:android:d3bd5f553074e42a1ad695',
    messagingSenderId: '848467584016',
    projectId: 'restaurant-project-237e9',
    storageBucket: 'restaurant-project-237e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNXB9CzS3WWlhCJ9VFLoFxqiSYpkXdEkA',
    appId: '1:848467584016:ios:d118c18a0fdcf8cb1ad695',
    messagingSenderId: '848467584016',
    projectId: 'restaurant-project-237e9',
    storageBucket: 'restaurant-project-237e9.firebasestorage.app',
    iosClientId: '848467584016-iloln4s9oqurqa4vi1bvi446ddgjj3b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );

}