// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLY_nMp9Sbpv9gUlx9k5GB5NWpIP1dUY',
    appId: '1:197262601504:web:8a409f9b23bc7ce28abb45',
    messagingSenderId: '197262601504',
    projectId: 'restaurant-85689',
    authDomain: 'restaurant-85689.firebaseapp.com',
    storageBucket: 'restaurant-85689.firebasestorage.app',
    measurementId: 'G-J4KV38QH2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCN1uJcvNFFKLc02PhMcDlVltig9rnKg',
    appId: '1:197262601504:android:f1afa0086b97de828abb45',
    messagingSenderId: '197262601504',
    projectId: 'restaurant-85689',
    storageBucket: 'restaurant-85689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHwzkVM7KfnvcPFA07FlhKVLfyAV4mwQ',
    appId: '1:197262601504:ios:228d7659241c05088abb45',
    messagingSenderId: '197262601504',
    projectId: 'restaurant-85689',
    storageBucket: 'restaurant-85689.firebasestorage.app',
    iosBundleId: 'com.example.googleMapsInFlutter',
  );

}

